//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MoveitTaskConstructorMsgs
{
    [Serializable]
    public class ExecuteTaskSolutionFeedback : Message
    {
        public const string k_RosMessageName = "moveit_task_constructor_msgs/ExecuteTaskSolution";
        public override string RosMessageName => k_RosMessageName;

        public uint sub_id;
        public uint sub_no;

        public ExecuteTaskSolutionFeedback()
        {
        }

        public ExecuteTaskSolutionFeedback(uint subId, uint subNo)
        {
            sub_id = subId;
            sub_no = subNo;
        }

        public static ExecuteTaskSolutionFeedback Deserialize(MessageDeserializer deserializer) =>
            new ExecuteTaskSolutionFeedback(deserializer);

        ExecuteTaskSolutionFeedback(MessageDeserializer deserializer)
        {
            deserializer.Read(out sub_id);
            deserializer.Read(out sub_no);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(sub_id);
            serializer.Write(sub_no);
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
