//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MoveitTaskConstructorMsgs
{
    [Serializable]
    public class ExecuteTaskSolutionGoal : Message
    {
        public const string k_RosMessageName = "moveit_task_constructor_msgs/ExecuteTaskSolution";
        public override string RosMessageName => k_RosMessageName;

        public SolutionMsg solution;

        public ExecuteTaskSolutionGoal()
        {
            solution = new SolutionMsg();
        }

        public ExecuteTaskSolutionGoal(SolutionMsg solution)
        {
            this.solution = solution;
        }

        public static ExecuteTaskSolutionGoal Deserialize(MessageDeserializer deserializer) =>
            new ExecuteTaskSolutionGoal(deserializer);

        ExecuteTaskSolutionGoal(MessageDeserializer deserializer)
        {
            solution = SolutionMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(solution);
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
