//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class ServoStatusMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/ServoStatus";
        public override string RosMessageName => k_RosMessageName;

        //  Message
        public sbyte code;
        //  will contains integer code
        public string message;
        //  will contain explanatory message
        //  Status types (should reflect StatusCode from moveit_servo/utils/datatype.hpp)
        public const sbyte INVALID = -1;
        public const sbyte NO_WARNING = 0;
        public const sbyte DECELERATE_FOR_APPROACHING_SINGULARITY = 1;
        public const sbyte HALT_FOR_SINGULARITY = 2;
        public const sbyte DECELERATE_FOR_LEAVING_SINGULARITY = 3;
        public const sbyte DECELERATE_FOR_COLLISION = 4;
        public const sbyte HALT_FOR_COLLISION = 5;
        public const sbyte JOINT_BOUND = 6;

        public ServoStatusMsg()
        {
            this.code = 0;
            this.message = "";
        }

        public ServoStatusMsg(sbyte code, string message)
        {
            this.code = code;
            this.message = message;
        }

        public static ServoStatusMsg Deserialize(MessageDeserializer deserializer) => new ServoStatusMsg(deserializer);

        private ServoStatusMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.code);
            deserializer.Read(out this.message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.code);
            serializer.Write(this.message);
        }

        public override string ToString()
        {
            return "ServoStatusMsg: " +
            "\ncode: " + code.ToString() +
            "\nmessage: " + message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
