//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.StudyInterfaces
{
    [Serializable]
    public class GetSolutionResponse : Message
    {
        public const string k_RosMessageName = "study_interfaces/GetSolution";
        public override string RosMessageName => k_RosMessageName;

        public bool success;
        public string message;
        public MoveitTaskConstructorMsgs.SolutionMsg solution;

        public GetSolutionResponse()
        {
            this.success = false;
            this.message = "";
            this.solution = new MoveitTaskConstructorMsgs.SolutionMsg();
        }

        public GetSolutionResponse(bool success, string message, MoveitTaskConstructorMsgs.SolutionMsg solution)
        {
            this.success = success;
            this.message = message;
            this.solution = solution;
        }

        public static GetSolutionResponse Deserialize(MessageDeserializer deserializer) => new GetSolutionResponse(deserializer);

        private GetSolutionResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
            deserializer.Read(out this.message);
            this.solution = MoveitTaskConstructorMsgs.SolutionMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
            serializer.Write(this.message);
            serializer.Write(this.solution);
        }

        public override string ToString()
        {
            return "GetSolutionResponse: " +
            "\nsuccess: " + success.ToString() +
            "\nmessage: " + message.ToString() +
            "\nsolution: " + solution.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
