//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.StudyInterfaces
{
    [Serializable]
    public class GetSolutionRequest : Message
    {
        public const string k_RosMessageName = "study_interfaces/GetSolution";
        public override string RosMessageName => k_RosMessageName;

        public string task_id;
        public uint solution_id;
        public bool include_start_scene;

        public GetSolutionRequest()
        {
            this.task_id = "";
            this.solution_id = 0;
            this.include_start_scene = false;
        }

        public GetSolutionRequest(string task_id, uint solution_id, bool include_start_scene)
        {
            this.task_id = task_id;
            this.solution_id = solution_id;
            this.include_start_scene = include_start_scene;
        }

        public static GetSolutionRequest Deserialize(MessageDeserializer deserializer) => new GetSolutionRequest(deserializer);

        private GetSolutionRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.task_id);
            deserializer.Read(out this.solution_id);
            deserializer.Read(out this.include_start_scene);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.task_id);
            serializer.Write(this.solution_id);
            serializer.Write(this.include_start_scene);
        }

        public override string ToString()
        {
            return "GetSolutionRequest: " +
            "\ntask_id: " + task_id.ToString() +
            "\nsolution_id: " + solution_id.ToString() +
            "\ninclude_start_scene: " + include_start_scene.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
