//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using RosMessageTypes.Moveit;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MoveitTaskConstructorMsgs
{
    [Serializable]
    public class ExecuteTaskSolutionResult : Message
    {
        public const string k_RosMessageName = "moveit_task_constructor_msgs/ExecuteTaskSolution";
        public override string RosMessageName => k_RosMessageName;

        public MoveItErrorCodesMsg error_code;

        public ExecuteTaskSolutionResult()
        {
            error_code = new MoveItErrorCodesMsg();
        }

        public ExecuteTaskSolutionResult(MoveItErrorCodesMsg errorCode)
        {
            error_code = errorCode;
        }

        public static ExecuteTaskSolutionResult Deserialize(MessageDeserializer deserializer) =>
            new ExecuteTaskSolutionResult(deserializer);

        ExecuteTaskSolutionResult(MessageDeserializer deserializer)
        {
            error_code = MoveItErrorCodesMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(error_code);
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
