//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class GetGroupUrdfResponse : Message
    {
        public const string k_RosMessageName = "moveit_msgs/GetGroupUrdf";
        public override string RosMessageName => k_RosMessageName;

        //  Whether an error occurred
        public MoveItErrorCodesMsg error_code;
        //  URDF of the requested group. Empty if request was not successful e.g. because the group does not exist
        public string urdf_string;

        public GetGroupUrdfResponse()
        {
            this.error_code = new MoveItErrorCodesMsg();
            this.urdf_string = "";
        }

        public GetGroupUrdfResponse(MoveItErrorCodesMsg error_code, string urdf_string)
        {
            this.error_code = error_code;
            this.urdf_string = urdf_string;
        }

        public static GetGroupUrdfResponse Deserialize(MessageDeserializer deserializer) => new GetGroupUrdfResponse(deserializer);

        private GetGroupUrdfResponse(MessageDeserializer deserializer)
        {
            this.error_code = MoveItErrorCodesMsg.Deserialize(deserializer);
            deserializer.Read(out this.urdf_string);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.error_code);
            serializer.Write(this.urdf_string);
        }

        public override string ToString()
        {
            return "GetGroupUrdfResponse: " +
            "\nerror_code: " + error_code.ToString() +
            "\nurdf_string: " + urdf_string.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
