//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class ExecuteTrajectoryGoal : Message
    {
        public const string k_RosMessageName = "moveit_msgs/ExecuteTrajectory";
        public override string RosMessageName => k_RosMessageName;

        //  The trajectory to execute
        public RobotTrajectoryMsg trajectory;
        //  The controller names to use for execution
        public string[] controller_names;

        public ExecuteTrajectoryGoal()
        {
            this.trajectory = new RobotTrajectoryMsg();
            this.controller_names = new string[0];
        }

        public ExecuteTrajectoryGoal(RobotTrajectoryMsg trajectory, string[] controller_names)
        {
            this.trajectory = trajectory;
            this.controller_names = controller_names;
        }

        public static ExecuteTrajectoryGoal Deserialize(MessageDeserializer deserializer) => new ExecuteTrajectoryGoal(deserializer);

        private ExecuteTrajectoryGoal(MessageDeserializer deserializer)
        {
            this.trajectory = RobotTrajectoryMsg.Deserialize(deserializer);
            deserializer.Read(out this.controller_names, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.trajectory);
            serializer.WriteLength(this.controller_names);
            serializer.Write(this.controller_names);
        }

        public override string ToString()
        {
            return "ExecuteTrajectoryGoal: " +
            "\ntrajectory: " + trajectory.ToString() +
            "\ncontroller_names: " + System.String.Join(", ", controller_names.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
