//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class GlobalPlannerGoal : Message
    {
        public const string k_RosMessageName = "moveit_msgs/GlobalPlanner";
        public override string RosMessageName => k_RosMessageName;

        //  Motion planning request to the global planner
        public string planning_group;
        public MotionSequenceRequestMsg motion_sequence;

        public GlobalPlannerGoal()
        {
            this.planning_group = "";
            this.motion_sequence = new MotionSequenceRequestMsg();
        }

        public GlobalPlannerGoal(string planning_group, MotionSequenceRequestMsg motion_sequence)
        {
            this.planning_group = planning_group;
            this.motion_sequence = motion_sequence;
        }

        public static GlobalPlannerGoal Deserialize(MessageDeserializer deserializer) => new GlobalPlannerGoal(deserializer);

        private GlobalPlannerGoal(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.planning_group);
            this.motion_sequence = MotionSequenceRequestMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.planning_group);
            serializer.Write(this.motion_sequence);
        }

        public override string ToString()
        {
            return "GlobalPlannerGoal: " +
            "\nplanning_group: " + planning_group.ToString() +
            "\nmotion_sequence: " + motion_sequence.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
