//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class GlobalPlannerResult : Message
    {
        public const string k_RosMessageName = "moveit_msgs/GlobalPlanner";
        public override string RosMessageName => k_RosMessageName;

        //  Motion planning response from the global planner
        public MotionPlanResponseMsg response;

        public GlobalPlannerResult()
        {
            this.response = new MotionPlanResponseMsg();
        }

        public GlobalPlannerResult(MotionPlanResponseMsg response)
        {
            this.response = response;
        }

        public static GlobalPlannerResult Deserialize(MessageDeserializer deserializer) => new GlobalPlannerResult(deserializer);

        private GlobalPlannerResult(MessageDeserializer deserializer)
        {
            this.response = MotionPlanResponseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.response);
        }

        public override string ToString()
        {
            return "GlobalPlannerResult: " +
            "\nresponse: " + response.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
