//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class HybridPlannerFeedback : Message
    {
        public const string k_RosMessageName = "moveit_msgs/HybridPlanner";
        public override string RosMessageName => k_RosMessageName;

        //  Feedback about the hybrid planning
        public string feedback;

        public HybridPlannerFeedback()
        {
            this.feedback = "";
        }

        public HybridPlannerFeedback(string feedback)
        {
            this.feedback = feedback;
        }

        public static HybridPlannerFeedback Deserialize(MessageDeserializer deserializer) => new HybridPlannerFeedback(deserializer);

        private HybridPlannerFeedback(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.feedback);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.feedback);
        }

        public override string ToString()
        {
            return "HybridPlannerFeedback: " +
            "\nfeedback: " + feedback.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
