//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class LocalPlannerFeedback : Message
    {
        public const string k_RosMessageName = "moveit_msgs/LocalPlanner";
        public override string RosMessageName => k_RosMessageName;

        //  Feedback about the currently running local planning operation
        public string feedback;

        public LocalPlannerFeedback()
        {
            this.feedback = "";
        }

        public LocalPlannerFeedback(string feedback)
        {
            this.feedback = feedback;
        }

        public static LocalPlannerFeedback Deserialize(MessageDeserializer deserializer) => new LocalPlannerFeedback(deserializer);

        private LocalPlannerFeedback(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.feedback);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.feedback);
        }

        public override string ToString()
        {
            return "LocalPlannerFeedback: " +
            "\nfeedback: " + feedback.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
