//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class PipelineStateMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/PipelineState";
        public override string RosMessageName => k_RosMessageName;

        //  Motion plan response that is processed
        public MotionPlanRequestMsg request;
        //  Current solution
        public MotionPlanResponseMsg response;
        //  Latest stage of the planning pipeline that got invoked
        public string pipeline_stage;

        public PipelineStateMsg()
        {
            this.request = new MotionPlanRequestMsg();
            this.response = new MotionPlanResponseMsg();
            this.pipeline_stage = "";
        }

        public PipelineStateMsg(MotionPlanRequestMsg request, MotionPlanResponseMsg response, string pipeline_stage)
        {
            this.request = request;
            this.response = response;
            this.pipeline_stage = pipeline_stage;
        }

        public static PipelineStateMsg Deserialize(MessageDeserializer deserializer) => new PipelineStateMsg(deserializer);

        private PipelineStateMsg(MessageDeserializer deserializer)
        {
            this.request = MotionPlanRequestMsg.Deserialize(deserializer);
            this.response = MotionPlanResponseMsg.Deserialize(deserializer);
            deserializer.Read(out this.pipeline_stage);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.request);
            serializer.Write(this.response);
            serializer.Write(this.pipeline_stage);
        }

        public override string ToString()
        {
            return "PipelineStateMsg: " +
            "\nrequest: " + request.ToString() +
            "\nresponse: " + response.ToString() +
            "\npipeline_stage: " + pipeline_stage.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
