//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.StudyInterfaces
{
    [Serializable]
    public class ObjectEventMsg : Message
    {
        public const string k_RosMessageName = "study_interfaces/ObjectEvent";
        public override string RosMessageName => k_RosMessageName;

        public string participant_id;
        //  "object_created" | "object_deleted" | "grab_start" | "grab_end" | "object_moved" | "edit_operation"
        public string event_type;
        public string object_id;
        public string scene_name;
        //  0-based index into StudyPlan.tasks
        public int task_index;
        //  0-based index into tasks[task_index].scene_names
        public int scene_index;
        //  Populated for grab_end / object_moved; zero/identity otherwise
        public Geometry.PoseMsg pose;
        //  Populated for resize edit operations; zero otherwise
        public Geometry.Vector3Msg scale;
        //  Free-form extra info, e.g. "resize:Cube:X:+0.35" or "snap"; empty when unused
        public string details;
        public BuiltinInterfaces.TimeMsg stamp;

        public ObjectEventMsg()
        {
            this.participant_id = "";
            this.event_type = "";
            this.object_id = "";
            this.scene_name = "";
            this.task_index = 0;
            this.scene_index = 0;
            this.pose = new Geometry.PoseMsg();
            this.scale = new Geometry.Vector3Msg();
            this.details = "";
            this.stamp = new BuiltinInterfaces.TimeMsg();
        }

        public ObjectEventMsg(string participant_id, string event_type, string object_id, string scene_name, int task_index, int scene_index, Geometry.PoseMsg pose, Geometry.Vector3Msg scale, string details, BuiltinInterfaces.TimeMsg stamp)
        {
            this.participant_id = participant_id;
            this.event_type = event_type;
            this.object_id = object_id;
            this.scene_name = scene_name;
            this.task_index = task_index;
            this.scene_index = scene_index;
            this.pose = pose;
            this.scale = scale;
            this.details = details;
            this.stamp = stamp;
        }

        public static ObjectEventMsg Deserialize(MessageDeserializer deserializer) => new ObjectEventMsg(deserializer);

        private ObjectEventMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.participant_id);
            deserializer.Read(out this.event_type);
            deserializer.Read(out this.object_id);
            deserializer.Read(out this.scene_name);
            deserializer.Read(out this.task_index);
            deserializer.Read(out this.scene_index);
            this.pose = Geometry.PoseMsg.Deserialize(deserializer);
            this.scale = Geometry.Vector3Msg.Deserialize(deserializer);
            deserializer.Read(out this.details);
            this.stamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.participant_id);
            serializer.Write(this.event_type);
            serializer.Write(this.object_id);
            serializer.Write(this.scene_name);
            serializer.Write(this.task_index);
            serializer.Write(this.scene_index);
            serializer.Write(this.pose);
            serializer.Write(this.scale);
            serializer.Write(this.details);
            serializer.Write(this.stamp);
        }

        public override string ToString()
        {
            return "ObjectEventMsg: " +
            "\nparticipant_id: " + participant_id.ToString() +
            "\nevent_type: " + event_type.ToString() +
            "\nobject_id: " + object_id.ToString() +
            "\nscene_name: " + scene_name.ToString() +
            "\ntask_index: " + task_index.ToString() +
            "\nscene_index: " + scene_index.ToString() +
            "\npose: " + pose.ToString() +
            "\nscale: " + scale.ToString() +
            "\ndetails: " + details.ToString() +
            "\nstamp: " + stamp.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
