//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.StudyInterfaces
{
    [Serializable]
    public class StudyPlanMsg : Message
    {
        public const string k_RosMessageName = "study_interfaces/StudyPlan";
        public override string RosMessageName => k_RosMessageName;

        public string participant_id;
        public TaskPlanMsg[] tasks;

        public StudyPlanMsg()
        {
            this.participant_id = "";
            this.tasks = new TaskPlanMsg[0];
        }

        public StudyPlanMsg(string participant_id, TaskPlanMsg[] tasks)
        {
            this.participant_id = participant_id;
            this.tasks = tasks;
        }

        public static StudyPlanMsg Deserialize(MessageDeserializer deserializer) => new StudyPlanMsg(deserializer);

        private StudyPlanMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.participant_id);
            deserializer.Read(out this.tasks, TaskPlanMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.participant_id);
            serializer.WriteLength(this.tasks);
            serializer.Write(this.tasks);
        }

        public override string ToString()
        {
            return "StudyPlanMsg: " +
            "\nparticipant_id: " + participant_id.ToString() +
            "\ntasks: " + System.String.Join(", ", tasks.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
