//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.StudyInterfaces
{
    [Serializable]
    public class StudyEventMsg : Message
    {
        public const string k_RosMessageName = "study_interfaces/StudyEvent";
        public override string RosMessageName => k_RosMessageName;

        public string participant_id;
        //  "scene_enter" | "scene_exit" (more types may be added later)
        public string event_type;
        public string scene_name;
        //  0-based index into StudyPlan.tasks
        public int task_index;
        //  0-based index into tasks[task_index].scene_names
        public int scene_index;
        //  Time spent in the scene; 0 for "scene_enter", elapsed time for "scene_exit"
        public double duration_sec;
        public BuiltinInterfaces.TimeMsg stamp;

        public StudyEventMsg()
        {
            this.participant_id = "";
            this.event_type = "";
            this.scene_name = "";
            this.task_index = 0;
            this.scene_index = 0;
            this.duration_sec = 0.0;
            this.stamp = new BuiltinInterfaces.TimeMsg();
        }

        public StudyEventMsg(string participant_id, string event_type, string scene_name, int task_index, int scene_index, double duration_sec, BuiltinInterfaces.TimeMsg stamp)
        {
            this.participant_id = participant_id;
            this.event_type = event_type;
            this.scene_name = scene_name;
            this.task_index = task_index;
            this.scene_index = scene_index;
            this.duration_sec = duration_sec;
            this.stamp = stamp;
        }

        public static StudyEventMsg Deserialize(MessageDeserializer deserializer) => new StudyEventMsg(deserializer);

        private StudyEventMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.participant_id);
            deserializer.Read(out this.event_type);
            deserializer.Read(out this.scene_name);
            deserializer.Read(out this.task_index);
            deserializer.Read(out this.scene_index);
            deserializer.Read(out this.duration_sec);
            this.stamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.participant_id);
            serializer.Write(this.event_type);
            serializer.Write(this.scene_name);
            serializer.Write(this.task_index);
            serializer.Write(this.scene_index);
            serializer.Write(this.duration_sec);
            serializer.Write(this.stamp);
        }

        public override string ToString()
        {
            return "StudyEventMsg: " +
            "\nparticipant_id: " + participant_id.ToString() +
            "\nevent_type: " + event_type.ToString() +
            "\nscene_name: " + scene_name.ToString() +
            "\ntask_index: " + task_index.ToString() +
            "\nscene_index: " + scene_index.ToString() +
            "\nduration_sec: " + duration_sec.ToString() +
            "\nstamp: " + stamp.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
