//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.StudyInterfaces
{
    [Serializable]
    public class TaskPlanMsg : Message
    {
        public const string k_RosMessageName = "study_interfaces/TaskPlan";
        public override string RosMessageName => k_RosMessageName;

        public string interlude_scene;
        public string[] scene_names;

        public TaskPlanMsg()
        {
            this.interlude_scene = "";
            this.scene_names = new string[0];
        }

        public TaskPlanMsg(string interlude_scene, string[] scene_names)
        {
            this.interlude_scene = interlude_scene;
            this.scene_names = scene_names;
        }

        public static TaskPlanMsg Deserialize(MessageDeserializer deserializer) => new TaskPlanMsg(deserializer);

        private TaskPlanMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.interlude_scene);
            deserializer.Read(out this.scene_names, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.interlude_scene);
            serializer.WriteLength(this.scene_names);
            serializer.Write(this.scene_names);
        }

        public override string ToString()
        {
            return "TaskPlanMsg: " +
            "\ninterlude_scene: " + interlude_scene.ToString() +
            "\nscene_names: " + System.String.Join(", ", scene_names.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
