//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.StudyInterfaces
{
    [Serializable]
    public class PickPlaceFeedback : Message
    {
        public const string k_RosMessageName = "study_interfaces/PickPlace";
        public override string RosMessageName => k_RosMessageName;

        //  e.g. "planning", "executing"
        public string stage;

        public PickPlaceFeedback()
        {
            stage = "";
        }

        public PickPlaceFeedback(string stage)
        {
            this.stage = stage;
        }

        public static PickPlaceFeedback Deserialize(MessageDeserializer deserializer) =>
            new PickPlaceFeedback(deserializer);

        PickPlaceFeedback(MessageDeserializer deserializer)
        {
            deserializer.Read(out stage);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(stage);
        }

        public override string ToString()
        {
            return "PickPlaceFeedback: " +
            "\nstage: " + stage;
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
