//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.StudyInterfaces
{
    [Serializable]
    public class ExecuteSolutionGoal : Message
    {
        public const string k_RosMessageName = "study_interfaces/ExecuteSolution";
        public override string RosMessageName => k_RosMessageName;

        public string task_id;
        public uint solution_id;

        public ExecuteSolutionGoal()
        {
            this.task_id = "";
            this.solution_id = 0;
        }

        public ExecuteSolutionGoal(string task_id, uint solution_id)
        {
            this.task_id = task_id;
            this.solution_id = solution_id;
        }

        public static ExecuteSolutionGoal Deserialize(MessageDeserializer deserializer) => new ExecuteSolutionGoal(deserializer);

        private ExecuteSolutionGoal(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.task_id);
            deserializer.Read(out this.solution_id);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.task_id);
            serializer.Write(this.solution_id);
        }

        public override string ToString()
        {
            return "ExecuteSolutionGoal: " +
            "\ntask_id: " + task_id.ToString() +
            "\nsolution_id: " + solution_id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
