//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.StudyInterfaces
{
    [Serializable]
    public class ExecuteSolutionFeedback : Message
    {
        public const string k_RosMessageName = "study_interfaces/ExecuteSolution";
        public override string RosMessageName => k_RosMessageName;

        public uint sub_id;
        //  index of the finished sub-trajectory
        public uint sub_no;
        //  total number of sub-trajectories
        public uint stage_id;
        //  introspection stage id

        public ExecuteSolutionFeedback()
        {
            this.sub_id = 0;
            this.sub_no = 0;
            this.stage_id = 0;
        }

        public ExecuteSolutionFeedback(uint sub_id, uint sub_no, uint stage_id)
        {
            this.sub_id = sub_id;
            this.sub_no = sub_no;
            this.stage_id = stage_id;
        }

        public static ExecuteSolutionFeedback Deserialize(MessageDeserializer deserializer) => new ExecuteSolutionFeedback(deserializer);

        private ExecuteSolutionFeedback(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.sub_id);
            deserializer.Read(out this.sub_no);
            deserializer.Read(out this.stage_id);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.sub_id);
            serializer.Write(this.sub_no);
            serializer.Write(this.stage_id);
        }

        public override string ToString()
        {
            return "ExecuteSolutionFeedback: " +
            "\nsub_id: " + sub_id.ToString() +
            "\nsub_no: " + sub_no.ToString() +
            "\nstage_id: " + stage_id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
