//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.StudyInterfaces
{
    [Serializable]
    public class ExecuteSolutionResult : Message
    {
        public const string k_RosMessageName = "study_interfaces/ExecuteSolution";
        public override string RosMessageName => k_RosMessageName;

        public bool success;
        public string message;
        public Moveit.MoveItErrorCodesMsg error_code;

        public ExecuteSolutionResult()
        {
            this.success = false;
            this.message = "";
            this.error_code = new Moveit.MoveItErrorCodesMsg();
        }

        public ExecuteSolutionResult(bool success, string message, Moveit.MoveItErrorCodesMsg error_code)
        {
            this.success = success;
            this.message = message;
            this.error_code = error_code;
        }

        public static ExecuteSolutionResult Deserialize(MessageDeserializer deserializer) => new ExecuteSolutionResult(deserializer);

        private ExecuteSolutionResult(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
            deserializer.Read(out this.message);
            this.error_code = Moveit.MoveItErrorCodesMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
            serializer.Write(this.message);
            serializer.Write(this.error_code);
        }

        public override string ToString()
        {
            return "ExecuteSolutionResult: " +
            "\nsuccess: " + success.ToString() +
            "\nmessage: " + message.ToString() +
            "\nerror_code: " + error_code.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
