//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.StudyInterfaces
{
    [Serializable]
    public class PickPlaceFeedback : Message
    {
        public const string k_RosMessageName = "study_interfaces/PickPlace";
        public override string RosMessageName => k_RosMessageName;

        public string task_id;
        //  empty on the first message, set from then on
        public string stage;
        //  "initializing" | "planning" | "executing"
        public uint solutions_found;
        public float best_cost;
        //  +Infinity until a solution is found

        public PickPlaceFeedback()
        {
            this.task_id = "";
            this.stage = "";
            this.solutions_found = 0;
            this.best_cost = 0.0f;
        }

        public PickPlaceFeedback(string task_id, string stage, uint solutions_found, float best_cost)
        {
            this.task_id = task_id;
            this.stage = stage;
            this.solutions_found = solutions_found;
            this.best_cost = best_cost;
        }

        public static PickPlaceFeedback Deserialize(MessageDeserializer deserializer) => new PickPlaceFeedback(deserializer);

        private PickPlaceFeedback(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.task_id);
            deserializer.Read(out this.stage);
            deserializer.Read(out this.solutions_found);
            deserializer.Read(out this.best_cost);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.task_id);
            serializer.Write(this.stage);
            serializer.Write(this.solutions_found);
            serializer.Write(this.best_cost);
        }

        public override string ToString()
        {
            return "PickPlaceFeedback: " +
            "\ntask_id: " + task_id.ToString() +
            "\nstage: " + stage.ToString() +
            "\nsolutions_found: " + solutions_found.ToString() +
            "\nbest_cost: " + best_cost.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
