//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.StudyInterfaces
{
    [Serializable]
    public class PickPlaceGoal : Message
    {
        public const string k_RosMessageName = "study_interfaces/PickPlace";
        public override string RosMessageName => k_RosMessageName;

        public string object_id;
        public Geometry.PoseStampedMsg place_pose;
        public Moveit.PlanningSceneMsg start_scene_diff;
        //  optional; empty = no-op
        public bool execute;
        //  false = plan only (what the browser uses). ROS 2 default: true (set by hand; the generator ignores defaults)
        public uint max_solutions;
        //  0 = server default

        public PickPlaceGoal()
        {
            this.object_id = "";
            this.place_pose = new Geometry.PoseStampedMsg();
            this.start_scene_diff = new Moveit.PlanningSceneMsg();
            this.execute = true;
            this.max_solutions = 0;
        }

        public PickPlaceGoal(string object_id, Geometry.PoseStampedMsg place_pose, Moveit.PlanningSceneMsg start_scene_diff, bool execute, uint max_solutions)
        {
            this.object_id = object_id;
            this.place_pose = place_pose;
            this.start_scene_diff = start_scene_diff;
            this.execute = execute;
            this.max_solutions = max_solutions;
        }

        public static PickPlaceGoal Deserialize(MessageDeserializer deserializer) => new PickPlaceGoal(deserializer);

        private PickPlaceGoal(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.object_id);
            this.place_pose = Geometry.PoseStampedMsg.Deserialize(deserializer);
            this.start_scene_diff = Moveit.PlanningSceneMsg.Deserialize(deserializer);
            deserializer.Read(out this.execute);
            deserializer.Read(out this.max_solutions);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.object_id);
            serializer.Write(this.place_pose);
            serializer.Write(this.start_scene_diff);
            serializer.Write(this.execute);
            serializer.Write(this.max_solutions);
        }

        public override string ToString()
        {
            return "PickPlaceGoal: " +
            "\nobject_id: " + object_id.ToString() +
            "\nplace_pose: " + place_pose.ToString() +
            "\nstart_scene_diff: " + start_scene_diff.ToString() +
            "\nexecute: " + execute.ToString() +
            "\nmax_solutions: " + max_solutions.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
