//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.StudyInterfaces
{
    [Serializable]
    public class PickPlaceGoal : Message
    {
        public const string k_RosMessageName = "study_interfaces/PickPlace";
        public override string RosMessageName => k_RosMessageName;

        //  Pick up `object_id` from its current pose in the live planning scene
        //  and place it at `place_pose`.
        public string object_id;
        public Geometry.PoseStampedMsg place_pose;
        //  true: plan and execute. false: plan only.
        public bool execute;

        public PickPlaceGoal()
        {
            object_id = "";
            place_pose = new Geometry.PoseStampedMsg();
            execute = true;
        }

        public PickPlaceGoal(string object_id, Geometry.PoseStampedMsg place_pose, bool execute)
        {
            this.object_id = object_id;
            this.place_pose = place_pose;
            this.execute = execute;
        }

        public static PickPlaceGoal Deserialize(MessageDeserializer deserializer) =>
            new PickPlaceGoal(deserializer);

        PickPlaceGoal(MessageDeserializer deserializer)
        {
            deserializer.Read(out object_id);
            place_pose = Geometry.PoseStampedMsg.Deserialize(deserializer);
            deserializer.Read(out execute);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(object_id);
            serializer.Write(place_pose);
            serializer.Write(execute);
        }

        public override string ToString()
        {
            return "PickPlaceGoal: " +
            "\nobject_id: " + object_id +
            "\nplace_pose: " + place_pose +
            "\nexecute: " + execute;
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
