//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.StudyInterfaces
{
    [Serializable]
    public class PickPlaceResult : Message
    {
        public const string k_RosMessageName = "study_interfaces/PickPlace";
        public override string RosMessageName => k_RosMessageName;

        public bool success;
        public string message;

        public PickPlaceResult()
        {
            message = "";
        }

        public PickPlaceResult(bool success, string message)
        {
            this.success = success;
            this.message = message;
        }

        public static PickPlaceResult Deserialize(MessageDeserializer deserializer) =>
            new PickPlaceResult(deserializer);

        PickPlaceResult(MessageDeserializer deserializer)
        {
            deserializer.Read(out success);
            deserializer.Read(out message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(success);
            serializer.Write(message);
        }

        public override string ToString()
        {
            return "PickPlaceResult: " +
            "\nsuccess: " + success +
            "\nmessage: " + message;
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
