//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class GetGroupUrdfRequest : Message
    {
        public const string k_RosMessageName = "moveit_msgs/GetGroupUrdf";
        public override string RosMessageName => k_RosMessageName;

        //  Name of the planning group for which an URDF is requested
        public string group_name;

        public GetGroupUrdfRequest()
        {
            this.group_name = "";
        }

        public GetGroupUrdfRequest(string group_name)
        {
            this.group_name = group_name;
        }

        public static GetGroupUrdfRequest Deserialize(MessageDeserializer deserializer) => new GetGroupUrdfRequest(deserializer);

        private GetGroupUrdfRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.group_name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.group_name);
        }

        public override string ToString()
        {
            return "GetGroupUrdfRequest: " +
            "\ngroup_name: " + group_name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
