//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class GetMultiStateValidityRequest : Message
    {
        public const string k_RosMessageName = "moveit_msgs/GetMultiStateValidity";
        public override string RosMessageName => k_RosMessageName;

        public RobotStateMsg robot_state;
        public Sensor.JointStateMsg[] joint_states;
        public string group_name;
        public ConstraintsMsg constraints;

        public GetMultiStateValidityRequest()
        {
            this.robot_state = new RobotStateMsg();
            this.joint_states = new Sensor.JointStateMsg[0];
            this.group_name = "";
            this.constraints = new ConstraintsMsg();
        }

        public GetMultiStateValidityRequest(RobotStateMsg robot_state, Sensor.JointStateMsg[] joint_states, string group_name, ConstraintsMsg constraints)
        {
            this.robot_state = robot_state;
            this.joint_states = joint_states;
            this.group_name = group_name;
            this.constraints = constraints;
        }

        public static GetMultiStateValidityRequest Deserialize(MessageDeserializer deserializer) => new GetMultiStateValidityRequest(deserializer);

        private GetMultiStateValidityRequest(MessageDeserializer deserializer)
        {
            this.robot_state = RobotStateMsg.Deserialize(deserializer);
            deserializer.Read(out this.joint_states, Sensor.JointStateMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.group_name);
            this.constraints = ConstraintsMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.robot_state);
            serializer.WriteLength(this.joint_states);
            serializer.Write(this.joint_states);
            serializer.Write(this.group_name);
            serializer.Write(this.constraints);
        }

        public override string ToString()
        {
            return "GetMultiStateValidityRequest: " +
            "\nrobot_state: " + robot_state.ToString() +
            "\njoint_states: " + System.String.Join(", ", joint_states.ToList()) +
            "\ngroup_name: " + group_name.ToString() +
            "\nconstraints: " + constraints.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
