//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class LoadGeometryFromFileRequest : Message
    {
        public const string k_RosMessageName = "moveit_msgs/LoadGeometryFromFile";
        public override string RosMessageName => k_RosMessageName;

        //  This service loads CollisionObjects from a .scene file into a PlanningScene
        public string file_path_and_name;

        public LoadGeometryFromFileRequest()
        {
            this.file_path_and_name = "";
        }

        public LoadGeometryFromFileRequest(string file_path_and_name)
        {
            this.file_path_and_name = file_path_and_name;
        }

        public static LoadGeometryFromFileRequest Deserialize(MessageDeserializer deserializer) => new LoadGeometryFromFileRequest(deserializer);

        private LoadGeometryFromFileRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.file_path_and_name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.file_path_and_name);
        }

        public override string ToString()
        {
            return "LoadGeometryFromFileRequest: " +
            "\nfile_path_and_name: " + file_path_and_name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
