//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class SaveGeometryToFileRequest : Message
    {
        public const string k_RosMessageName = "moveit_msgs/SaveGeometryToFile";
        public override string RosMessageName => k_RosMessageName;

        //  This service saves the CollisionObjects present in a PlanningScene to a .scene file
        public string file_path_and_name;

        public SaveGeometryToFileRequest()
        {
            this.file_path_and_name = "";
        }

        public SaveGeometryToFileRequest(string file_path_and_name)
        {
            this.file_path_and_name = file_path_and_name;
        }

        public static SaveGeometryToFileRequest Deserialize(MessageDeserializer deserializer) => new SaveGeometryToFileRequest(deserializer);

        private SaveGeometryToFileRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.file_path_and_name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.file_path_and_name);
        }

        public override string ToString()
        {
            return "SaveGeometryToFileRequest: " +
            "\nfile_path_and_name: " + file_path_and_name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
