//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class ServoCommandTypeRequest : Message
    {
        public const string k_RosMessageName = "moveit_msgs/ServoCommandType";
        public override string RosMessageName => k_RosMessageName;

        //  Request constants
        public const sbyte JOINT_JOG = 0;
        public const sbyte TWIST = 1;
        public const sbyte POSE = 2;
        //  Request Field
        public sbyte command_type;

        public ServoCommandTypeRequest()
        {
            this.command_type = 0;
        }

        public ServoCommandTypeRequest(sbyte command_type)
        {
            this.command_type = command_type;
        }

        public static ServoCommandTypeRequest Deserialize(MessageDeserializer deserializer) => new ServoCommandTypeRequest(deserializer);

        private ServoCommandTypeRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.command_type);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.command_type);
        }

        public override string ToString()
        {
            return "ServoCommandTypeRequest: " +
            "\ncommand_type: " + command_type.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
