//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MoveitTaskConstructorMsgs
{
    [Serializable]
    public class PickPlaceTaskMsg : Message
    {
        public const string k_RosMessageName = "moveit_task_constructor_msgs/PickPlaceTask";
        public override string RosMessageName => k_RosMessageName;

        //  Object to pick (must exist in the planning scene)
        public string object_id;
        //  Target pose where the object should be placed
        public Geometry.PoseStampedMsg place_pose;

        public PickPlaceTaskMsg()
        {
            this.object_id = "";
            this.place_pose = new Geometry.PoseStampedMsg();
        }

        public PickPlaceTaskMsg(string object_id, Geometry.PoseStampedMsg place_pose)
        {
            this.object_id = object_id;
            this.place_pose = place_pose;
        }

        public static PickPlaceTaskMsg Deserialize(MessageDeserializer deserializer) => new PickPlaceTaskMsg(deserializer);

        private PickPlaceTaskMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.object_id);
            this.place_pose = Geometry.PoseStampedMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.object_id);
            serializer.Write(this.place_pose);
        }

        public override string ToString()
        {
            return "PickPlaceTaskMsg: " +
            "\nobject_id: " + object_id.ToString() +
            "\nplace_pose: " + place_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
